server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://217.60.249.94:3306/personal_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: personal
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.share.model

auth:
  whitelist:
    - /error

user:
  auth: http://45.154.2.158:8081

share:
  url: http://45.154.2.158:8083/shared/

file:
  url: http://45.154.2.158:8080

third:
  auth:
    secret: 12345678